### ISSUE TITLE
F-Droid isn't seeing new releases, is currently stuck at 1.0

### ISSUE THREAD

**Issue by herbsmn** [robinpaulson/SimpleRT#37]
Can ya'll make sure that F-Droid can see it when you update SimpleRT and/or make sure it updates to the current stable release?

https://f-droid.org/packages/com.viper.simplert/
https://f-droid.org/wiki/page/com.viper.simplert
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.viper.simplert.txt
https://gitlab.com/fdroid/fdroiddata/issues/789

**Comment by herbsmn** [comment]
From the [gitlab issue](https://gitlab.com/fdroid/fdroiddata/issues/789#note_34304719):

"Both 1.0 and 1.1 have version code 1, so from Android's point of view this is the same version.

This needs to be solved by the app author: bump versionCode and versionName in build.gradle and then re-tag 1.1 release. After that we will be able to add a new build on F-Droid."

**Comment by herbsmn** [comment]
@vvviperrr any chance you can assist with this? is this the correct place to post issues?

**Comment by softwarecreations** [comment]
What needs to happen to
* Get the latest version of SimpleRT onto F-Droid?
* Get Eugene's commits into the new version (if they're good) https://github.com/eugene-sevostianov-sc/SimpleRT
* Get Fabian's commits into the new version (if they're good) https://github.com/iteratec/SimpleRT

@vvviperrr have you abandoned (or have no time for) this project?
Perhaps you can give access to people who would like to help, such as Eugene or Fabian?

Unfortunately I don't do any Android Dev myself. I'm a Linux guy, I do general programming, but no Java/Android. But I would also like to help where I can to make this project a success.

**Comment by fsobanski** [comment]
I will take a look at it on the weekend and see if I can publish my version (v1.2.3)[https://github.com/iteratec/SimpleRT/commit/4aa50bd473cf4aebefa058b922a881e045bd6e6d] onto F-Droid as a new app.

**Comment by robinpaulson** [comment]
Hi folks, take a look at #58

**Comment by robinpaulson** [comment]
I will be pushing a new release in the next week or so, I will make sure the version code, tag and release are all correct and compatible with the expectations of the F-Droid software.

**Comment by robinpaulson** [comment]
OK, I made a new release by bumping the version codes to get around the v1/v1.1 clash ... then realised there might be an error. I gather eugene's commits have been merged, do they fix the problem which stops it building?

**Comment by robinpaulson** [comment]
@fsobanski Where are you at with your dev work Fabian? I took a look through your repo at the extra commits you'd made on top of wiper's work.

I see you comment that simpleRT won't build on your system. Is that the original code, your mods or both?

**Comment by softwarecreations** [comment]
@robinpaulson @fsobanski has not been active on Github in the last year.
I think you should just run with stuff. Not wait around for @fschlich https://github.com/robinpaulson/SimpleRT/issues/49#issuecomment-586467848 to make a PR for a few trivial lines of shell script changes.

I think shove stuff together and just try it out, if it works, ship it.
Rather invite people to make PR's in future, let them know contributions are welcome in the future.
One can't wait around or expect people who've been silent on this previously totally dead project for a 1~3 years to suddenly spring to life etc. Maybe they don't have an Android dev environment setup, who knows.

This project has been totally dead and the best thing to bring it back to life and build a community is to get a working version on F-Droid ASAP.

So that's my 2c. By all means, good to reach out, but don't stop or slow down, wait or ask for anything. Just gogogo!

**Comment by robinpaulson** [comment]
I'll fess up ... I can't read diffs. I understand that comment by Florian contains changes, but I don't know how to understand it. I guess I should figure out how diff works, then make the changes myself.

**Comment by robinpaulson** [comment]
Of course, if I RTFM, I might figure it out.

Patches applied, possibly correctly.

**Comment by robinpaulson** [comment]
v1.1.1 release, it should be in fdroid within a week

**Comment by softwarecreations** [comment]
Well, that's how you learn bud. Git diffs are just + and -. + means a line was added - means removed.

**Comment by robinpaulson** [comment]
OK, it appears the new release built fine on the FD servers, it'll hit the tubes in the next day or so. Closing
